"""Maps REDCap variable names:accepted headers and values:values."""

shared_cols = [    
    'Record ID',
]

demographic_cols = {
    'race': {
        "Patient's race (choice=American Indian or Alaskan Native)": 'American Indian or Alaska Native',
        "Patient's race (choice=Asian)": 'Asian',
        "Patient's race (choice=Black or African American)": 'Black or African American',
        "Patient's race (choice=Native Hawaiian or Pacific Islander)": 'Native Hawaiian or Other Pacific Islander',
        "Patient's race (choice=White/Caucasian)": 'White',
        "Patient's race (choice=Unknown)": 'Other Race',
        },
    'ethnicity': {       
        "Patient's Ethnicity (choice=Hispanic)": 'Hispanic',
        "Patient's Ethnicity (choice=Not Hispanic)": 'Not-Hispanic',
        "Patient's Ethnicity (choice=Unknown)": 'Unknown',
    },
    "Patient's age": {
        "Patient's age": None,
    },
    "Patient's sex ": {
        "Male (transgender male)": 'M',
        "Female (transgender female)": 'F',
    },
    'To which facility did the patient present?': {
        'UW-Health - Madison': 'Dane',
        'Bellin Health - Green Bay': 'Brown',        
        'Bellin Health - Oconto': 'Oconto',
        'Medical College of Wisconsin - Milwaukee (Froedtert)': 'Milwaukee',
    }
}

form_props = {
    'spec': {
        'cols': 
            # ['Record ID'] +
            list(demographic_cols['race'].keys()) +
            list(demographic_cols['ethnicity'].keys()) +
            [
                "Patient's age",
                "Patient's sex ",
                'Survey Timestamp',
                'To which facility did the patient present?',
                'Complete?'
                ],
        'filt': 'Specimen Form',
    },
    'qtof': {
        'cols':  
            [
                'Specimen number',
                'Positive Ion Mode',
                'Negative Ion Mode',
                'Date of sample prep & QToF data acquisition',
                'Date received by WSLH',
                'Sample matrix',
                'Complete?.1'
            ],
        'filt': 'QToF Screen',
    }
}

test_not_done = [
    "LRNT150",
    "LRNT151",
    "LRNT152",
    "LRNT153",
    "LRNT154",
    "LRNT155",
    "LRNT156",
    "LRNT157",
]

tox_values = {
    'ALPRAZOLAM': '61038-6',
    'ALPHA-HYDROXYALPRAZOLAM': 'LRNT144',
    'CLONAZEPAM': '61039-4',
    '7-AMINOCLONAZEPAM': '61031-1',
    'DIAZEPAM': '61074-1',
    'NORDIAZEPAM': '61051-9',
    'OXAZEPAM': '61055-0',
    'TEMAZEPAM': '61061-8',
    'LORAZEPAM': '61044-4',
    'CLONAZOLAM': 'LRNT145',
    'ETIZOLAM': 'LRNT146',
    'FLUALPRAZOLAM': 'LRNT147',
    'FLUBROMAZOLAM': 'LRNT148',
    'DELTA-9 TETRAHYDROCANNABINOL': 'LRNT149',
    'THC (TETRAHYDROCANNABINOL)': 'LRNT149',
    'THC-M (CARBOXY METABOLITE)': '61063-4',
    'THC-M (CARBOXY THC-METABOLITE)': '61063-4',
    'THC-M (CARBOXY THC METABOLITE)': '61063-4',
    'THC-M (THC CARBOXY METABOLITE)': '61063-4',
    'COOH-THC': 'LRNT149',
    'THC-M (COOH-THC METAB)': 'LRNT149',
    'THC-CARBOXY': 'LRNT149',
    '11-HYDROXY DELTA-9 TETRAHYDROCANNABINOL': '48935-1',
    'THC-M (HYDROXY METABOLITE)': '48935-1',
    'THC-M (THC HYDROXY METABOLITE)': '48935-1',
    'OH-THC': '48935-1',
    'THC-OH': '48935-1',
    'THC-HYDROXY': '48935-1',
    'HYDROXY-THC': '48935-1',
    'DELTA-9 CARBOXY TETRAHYDROCANNABINOL': '61063-4',
    'DELTA-8 TETRAHYDROCANNABINOL': 'LRNT150',
    '11-HYDROXY DELTA-8 TETRAHYDROCANNABINOL': 'LRNT151',
    'DELTA-8 CARBOXY TETRAHYDROCANNABINOL': 'LRNT152',
    'DELTA-10 TETRAHYDROCANNABINOL': 'LRNT153',
    '11-HYDROXY DELTA-10 TETRAHYDROCANNABINOL': 'LRNT154',
    'DELTA-10 CARBOXY TETRAHYDROCANNABINOL': 'LRNT155',
    'DELTA-9 TETRAHYDROCANNABINOL-O-ACETATE': 'LRNT156',
    'THCP': 'LRNT157',
    'TETRAHYDROCANNABIPHOROL': 'LRNT157',
    'TETRAHYDROCANNABIPHOROL ISOMERS': 'LRNT157',
    '2F-DESCHLOROKETAMINE': 'LRNT158',
    '3-HYDROXYPHENCYCLIDINE-PHENCYCLIDINE': 'LRNT159',
    '4-HYDROXYPHENCYCLIDINE-PHENCYCLIDINE': 'LRNT160',
    'ALPHA-PYRROLIDINOHEXIOPHENONE': 'LRNT161',
    'ALPHA-PYRROLIDINOISOHEXANOPHENONE': 'LRNT162',
    'EUTYLONE': 'LRNT163',
    'N,N-DIMETHYL PENTYLONE': 'LRNT164',
    'ALPHA-PYRROLIDINOHEXIOPHENONE/ALPHA-PYRROLIDINOISOHEXANOPHENONE': 'LRNT192',
    '3-HYDROXYPHENCYCLIDINE-PHENCYCLIDINE/4-HYDROXYPHENCYCLIDINE-PHENCYCLIDINE': 'LRNT193',
    'FENTANYL': '61042-8',
    'NORFENTANYL': '61053-5',
    'FENTANYL-NOR': '61053-5',
    'CODEINE': '40626-4',
    'CODEINE-6-BETA-D-GLUCURONIDE': 'LRNT165',
    'CODEINE-6-GLUCURONIDE': 'LRNT165',
    'HYDROCODONE': '32080-4',
    'NORHYDROCODONE': 'LRNT166',
    'HYDROMORPHONE': '32081-2',
    'MORPHINE': '32100-0',
    'MORPHINE-3-GLUCURONIDE': 'LRNT167',
    'MORPHINE-6-GLUCURONIDE': 'LRNT168',
    'MORPHINE-3-BETA-D-GLUCURONIDE': 'LRNT167',
    'MORPHINE-6-BETA-D-GLUCURONIDE': 'LRNT168',
    'OXYCODONE': '32101-8',
    'OXYCODONE-NOR': 'LRNT169',
    'NOROXYCODONE': 'LRNT169',
    'OXYMORPHONE': 'LRNT170',
    '6-MONOACETYLMORPHINE': '32099-4',
    '6-MAM': '32099-4',
    'MORPHINE-6-MONOACETYL': '32099-4',
    'METHADONE': '32093-7',
    '2-ETHYLIDENE-1,5-DIMETHYL-3,3-DIPHENYLPYRROLIDINE': '41859-0',
    'EDDP': '41859-0',
    'BUPRENORPHINE': '82373-2',
    'NORBUPRENORPHINE': '82375-7',
    '4-ANILINO-N-PHENETHYLPIPERIDINE': 'LRNT171',
    '4-ANPP': 'LRNT171',
    '4-ANPP/DESPROPIONYLFENTANYL': 'LRNT171',
    'DESPROPIONYL FENTANYL': 'LRNT171',
    'DESPROPIONYLFENTANYL': 'LRNT171',
    'ACETYLFENTANYL': 'LRNT172',
    'FLUOROFENTANYL': 'LRNT173',
    'O/M/P-FLUOROFENTANYL': 'LRNT173',
    'PARA-FLUOROFENTANYL': 'LRNT174',
    'ORTHO-FLUOROFENTANYL': 'LRNT175',
    'META-FLUOROFENTANYL': 'LRNT176',
    'P-FLUOROFENTANYL': 'LRNT174',
    'O-FLUOROFENTANYL': 'LRNT175',
    'M-FLUOROFENTANYL': 'LRNT176',
    'CARFENTANIL': 'LRNT177',
    'NORCARFENTANIL': 'LRNT178',
    'TRAMADOL': 'LRNT179',
    'O-DESMETHYLTRAMADOL': 'LRNT180',
    'TRAMADOL-O-DESMETHYL': 'LRNT180',
    '2-METHYL-AP-237': 'LRNT181',
    'BRORPHINE': 'LRNT182',
    'ETODESNITAZENE': 'LRNT183',
    'ISOTONITAZENE': 'LRNT184',
    'METONITAZENE': 'LRNT185',
    'N-PYRROLIDINO ETONITAZENE': 'LRNT186',
    'PROTONITAZENE': 'LRNT187',
    'ISOTONITAZENE/PROTONITAZENE': 'LRNT194',
    'XYLAZINE': 'LRNT188',
    'GABAPENTIN': 'LRNT189',
    'AMPHETAMINES': '29530-3',
    'METHAMPHETAMINE': '40381-6',
    'COCAINE': '40625-6',
    'BENZOYLECGONINE': '40609-0',
    'COCAETHYLENE': 'LRNT195',
    'METHYLENEDIOXYAMPHETAMINE': '61046-9',
    'MDA': '61046-9',
    'METHYLENEDIOXYMETHAMPHETAMINE': '40481-4',
    'MDMA': '40481-4',
    'METHYLENEDIOXYETHYLAMPHETAMINE': '61049-3',
    'MDEA': '61049-3',
}

# Variable names must be mapped between REDCap export intermediate and CDC accepted fields.
var_names = {    
    'Record ID': 'Patient_ID', 
    'Specimen number': 'Specimen_ID', 
    "Patient's age": 'Patient_Age', 
    "Patient's sex ": 'Patient_Sex', 
    'Sample matrix': 'Sample_Type',
    'race': 'Patient_Race', 
    'ethnicity': 'Patient_Ethnicity',
    'Date received by WSLH': 'Received_dt',
    'Date of sample prep & QToF data acquisition': 'Test_dt',
    'Survey Timestamp': 'Collection_dt',
    'loinc': 'Analyte_LOINC',
    'result': 'Result_CODED',
    'To which facility did the patient present?': 'Patient_County',
}

result_CODED = {
    'Detected': '260373001',
    'Not detected': '260415000',
    'Equivocal result': '280414007',
    'Inconclusive': '419984006',
    'Test not done': '373121007',
}

default_vals = {
    'Activity_Type': 'OD2A',
    'Sample_Type': 'Urine',
    'Received_dt': 'Unknown',
    'Collection_dt': 'Unknown',
    'Sample_ID': '',
    'Run_ID': '',
    'Run_Create_dt': '',
    'Test_dt': 'Unknown',
    'Result_CODED': result_CODED['Not detected'],
    'Result_NUMERIC': '',
    'Unit_Of_Measure': '',
    'Analyte_Result_Comment': '',
    'Instrument_Type': 'LC/MS/MS',
    'Patient_State': '',
    'Patient_County': '',
    'Patient_Zip': '',
    'Patient_DOB': '',
    'Patient_Age': '',
    'Age_Unit': 'Year',
    'Patient_Sex': '',
    'Patient_Race': 'Other Race',
    'Patient_Ethnicity': 'Unknown',
    'Analyst': 'HB',
    'Reviewing_Official': ''
}
